# Pandas Exercises

In [6]:
import pandas as pd

url = "https://raw.githubusercontent.com/BeaverWorksMedlytics2020/Data_Public/master/NotebookExampleData/Week1/diabetes.csv"
names = ['preg', 'plas', 'pres', 'skin', 'test', 'mass', 'pedi', 'age', 'class']

Read in csv above to a pandas dataframe

In [7]:
# YOUR CODE HERE
# YOUR CODE HERE
data = pd.read_csv(url, names=names)

Print out the age and class of the 100th patient

In [8]:
# YOUR CODE HERE
print(f"Age of 100th patient: {data.loc[99, 'age']}")
print(f"Class of 100th patient: {data.loc[99, 'class']}")

Age of 100th patient: 31
Class of 100th patient: 1

Write code to figure out how many people are classified as not having diabetes, class is 0

In [9]:
# YOUR CODE HERE
non_diabetic = data[data['class'] == 0].shape[0]
print(f"Number of people without diabetes (class 0): {non_diabetic}")

Number of people without diabetes (class 0): 500

Write code to figure out how many people are classified as having diabetes, class is 1

In [10]:
# YOUR CODE HERE
diabetic_count = data[data['class'] == 1].shape[0]
print(f"Number of people with diabetes (class 1): {diabetic_count}")

Number of people with diabetes (class 1): 268

What percent of people have diabetes in the study

In [11]:
# YOUR CODE HERE
percent_diabetic = (diabetic_count / data.shape[0]) * 100
print(f"Percent of people with diabetes: {percent_diabetic}%")

Percent of people with diabetes: 34.89583333333333%

Print out the `"pres"` and `"class"` (no other columns) for the first 5 people

In [12]:
# YOUR CODE HERE
print(data[['pres', 'class']].head(5))

   pres  class
0    72      1
1    66      0
2    64      1
3    66      0
4    40      1

Run the cell below, it will print out the correlation among the columns

In [13]:
data.corr()

,preg,plas,pres,skin,test,mass,pedi,age,class
preg,1.000000,0.129459,0.141282,-0.081672,-0.073535,0.017683,-0.033523,0.544341,0.221898
plas,0.129459,1.000000,0.152590,0.057328,0.331357,0.221071,0.137337,0.263514,0.466581
pres,0.141282,0.152590,1.000000,0.207371,0.088933,0.281805,0.041265,0.239528,0.065068
skin,-0.081672,0.057328,0.207371,1.000000,0.436783,0.392573,0.183928,-0.113970,0.074752
test,-0.073535,0.331357,0.088933,0.436783,1.000000,0.197859,0.185071,-0.042163,0.130548
mass,0.017683,0.221071,0.281805,0.392573,0.197859,1.000000,0.140647,0.036242,0.292695
pedi,-0.033523,0.137337,0.041265,0.183928,0.185071,0.140647,1.000000,0.033561,0.173844
age,0.544341,0.263514,0.239528,-0.113970,-0.042163,0.036242,0.033561,1.000000,0.238356
class,0.221898,0.466581,0.065068,0.074752,0.130548,0.292695,0.173844,0.238356,1.000000

What column has the highest correlation with class? Find the mean() value of that column

In [14]:
# YOUR CODE HERE
correlation_with_class = data.corr()['class'].abs().sort_values(ascending=False)

highest_corr_column = correlation_with_class.index[1]

mean_of_column = data[highest_corr_column].mean()

print(f"Column with the highest correlation with 'class': {highest_corr_column}")
print(f"Mean of '{highest_corr_column}': {mean_of_column:.2f}")

Column with the highest correlation with 'class': plas
Mean of 'plas': 120.89

Create a new dataframe with only people that are above the mean found in the above cell.

In [15]:
# YOUR CODE HERE
df_above_plas_mean = data[data[highest_corr_column] > mean_of_column]
print(df_above_plas_mean.head())

   preg  plas  pres  skin  test  mass   pedi  age  class
0     6   148    72    35     0  33.6  0.627   50      1
2     8   183    64     0     0  23.3  0.672   32      1
4     0   137    40    35   168  43.1  2.288   33      1
8     2   197    70    45   543  30.5  0.158   53      1
9     8   125    96     0     0   0.0  0.232   54      1

Create a new dataframe that only includes people who are above the average value for each column in the dataset. In other words, find the average value for each column, and then find which users have values above all of these average column values.

In [16]:
column_means = data.mean()# YOUR CODE HERE
df_above_all_means = data[data > column_means].dropna()
print(df_above_all_means.head())

     preg   plas   pres  skin   test  mass   pedi   age  class
43    9.0  171.0  110.0  24.0  240.0  45.4  0.721  54.0    1.0
152   9.0  156.0   86.0  28.0  155.0  34.3  1.189  42.0    1.0
159  17.0  163.0   72.0  41.0  114.0  40.9  0.817  47.0    1.0
175   8.0  179.0   72.0  42.0  130.0  32.7  0.719  36.0    1.0
206   8.0  196.0   76.0  29.0  280.0  37.5  0.605  57.0    1.0

*Note: the next 3 problems were not explicitly shown in our tutorial—being able to effectively google and look through documentation is a very important coding tool!* ¯\\\_(ツ)_/¯

Ignoring the index (resetting the index to 0) and using the dataframe from the cell above, sort the values based on `"skin"`, `"test"`, and `"pedi"` values in ascending order. Please write this in one line.

In [17]:
# YOUR CODE HERE
df_sorted = df_above_all_means.sort_values(by=['skin', 'test', 'pedi'], ascending=True).reset_index(drop=True)
display(df_sorted)

    preg   plas   pres  skin   test  mass   pedi   age  class
0    7.0  181.0   84.0  21.0  192.0  35.9  0.586  51.0    1.0
1    9.0  171.0  110.0  24.0  240.0  45.4  0.721  54.0    1.0
2   11.0  138.0   74.0  26.0  144.0  36.1  0.557  50.0    1.0
3    5.0  187.0   76.0  27.0  207.0  43.6  1.034  53.0    1.0
4   11.0  155.0   76.0  28.0  150.0  33.3  1.353  51.0    1.0
5    9.0  156.0   86.0  28.0  155.0  34.3  1.189  42.0    1.0
6    7.0  150.0   78.0  29.0  126.0  35.2  0.692  54.0    1.0
7    8.0  196.0   76.0  29.0  280.0  37.5  0.605  57.0    1.0
8    8.0  151.0   78.0  32.0  210.0  42.9  0.516  36.0    1.0
9   12.0  151.0   70.0  40.0  271.0  41.8  0.742  38.0    1.0
10  17.0  163.0   72.0  41.0  114.0  40.9  0.817  47.0    1.0
11   8.0  179.0   72.0  42.0  130.0  32.7  0.719  36.0    1.0
12   7.0  168.0   88.0  42.0  321.0  38.2  0.787  40.0    1.0
13  12.0  140.0   82.0  43.0  325.0  39.2  0.528  58.0    1.0
14   9.0  145.0   80.0  46.0  130.0  37.9  0.637  40.0    1.0
15  10.0  148.0   84.0  48.0  237.0  37.6  1.001  51.0    1.0

Now let's find the 4 largest values for `"age"`

In [18]:
# YOUR CODE HERE
largest_ages = data['age'].nlargest(4)
print("The 4 largest values for 'age' are")
print(largest_ages)

The 4 largest values for 'age' are
459    81
453    72
666    70
123    69
Name: age, dtype: int64

Now find the smallest 4 values for `"pedi"` and `"plas"` in reverse order (smallest to largest).

In [19]:
#YOUR CODE HERE
smallest_pedi = data['pedi'].nsmallest(4)
print("The 4 smallest values for 'pedi' are")
print(smallest_pedi)

smallest_plas = data['plas'].nsmallest(4)
print("\nThe 4 smallest values for 'plas' are")
print(smallest_plas)

The 4 smallest values for 'pedi' are
268    0.078
180    0.084
149    0.085
567    0.085
Name: pedi, dtype: float64

The 4 smallest values for 'plas' are
75     0
182    0
342    0
349    0
Name: plas, dtype: int64